//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketID { get; set; }
        public string EmailID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> AssetID { get; set; }
        public string Message { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> DateOfCreation { get; set; }
        public Nullable<System.DateTime> DateOfModification { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual TicketCategory TicketCategory { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual TicketStatu TicketStatu { get; set; }
    }
}
