//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAsset
    {
        public int UserAssetID { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> AssetID { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
